### ISSUE TITLE
Filter not working with UUID field type

### ISSUE THREAD

**Issue by zeflaviodev** [enqueue/metabase-clickhouse-driver#70]
I'm creating a variable in a question with  field type UUID. When i filter, metabase add in query this code " CAST('XXXX-XXX-XXX', 'uuid')" 

![image](https://user-images.githubusercontent.com/44652644/126377219-88710380-b894-430c-9ec3-b7b7584f77d0.png)

In Clickhouse it is working when I change uuid lower case to upper case in cast  ex: CAST('XXXX-XXX-XXX', 'UUID').

how do I make the filter work with fields of type uuid ?

**Comment by enqueue** [comment]
Hi @zeflaviodev,

looking at your error message, it looks like you simply need to use upper-case "UUID" instead of lower-case "uuid".

I created a table like this:

```sql
CREATE TABLE foo
(
    `nase` String,
    `wert` UUID
)
ENGINE = Memory
```

and inserted some values

```sql
INSERT INTO foo (nase, wert) SELECT 'bar', generateUUIDv4();
INSERT INTO foo (nase, wert) SELECT 'baz', generateUUIDv4();
```

Now I go to Metabase and navigate to the table. This is what it looks like:

![uuid_metabase_1](https://user-images.githubusercontent.com/5407006/144713612-44aed73a-a1cc-42ce-afa6-f9df3677d4d7.png)

Now I can filter by that column:

![uuid_metabase_2](https://user-images.githubusercontent.com/5407006/144713870-902a81db-5c25-4df1-a691-17ce07d67c1d.gif)

I think you are referring to some native query, so let's see.

First try:

```sql
SELECT * from felix.foo WHERE wert = 'b0ff9244-400d-48f8-a13a-7565e9045fd8';
```

![uuid_metabase_3](https://user-images.githubusercontent.com/5407006/144714014-3b3bcb5d-3dc7-4832-9e6a-23ad05b70ff9.png)

Second try (with explicit casting):

```sql
SELECT * from felix.foo WHERE wert = CAST('b0ff9244-400d-48f8-a13a-7565e9045fd8', 'UUID');
```

![uuid_metabase_4](https://user-images.githubusercontent.com/5407006/144714030-3c64ae75-9ffc-4818-9f6b-4b232b2290a5.png)

This seems to work, too.

In the driver we try to make everything work with Metabase queries. If you want to use native queries, you should know what you are doing. However, please review the error message you are getting.

Have a great day and stay safe!
