### ISSUE TITLE
distinct result is not correct

### ISSUE THREAD

**Issue by hamzz** [enqueue/metabase-clickhouse-driver#71]
hi team, 

i do 'distinct' data using two different ways.

the first uses the distinct(id) method, the second uses the uniqExact(id) native query

but the result is different.

is it bug or not?

**Comment by enqueue** [comment]
Hi @hamzz :wave: and thank you for your report.

Of course you are right, that these differences should not happen.

We currently follow the ClickHouse recommendation (see [uniq manual entry](https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/reference/uniq/)):

> We recommend using this function in almost all scenarios.

So this is implemented when translating "distinct" Metabase questions into ClickHouse queries (see [lines 248ff. in clickhouse.clj](https://github.com/enqueue/metabase-clickhouse-driver/blob/3673d60b3cc2010ac48423c3e368640d2fad3764/src/metabase/driver/clickhouse.clj#L248)).

I would not mind removing this translation (as `COUNT(DISTINCT...` is translated into `uniqExact` automatically), because our application are relatively small. But I don't know about the other users, so I think it is safer to follow the recommendations. I am open to input from other users, though.

**Comment by enqueue** [comment]
I am going to change it to `uniqExact`.
